= Documentation

:sectnums:
== Conception fonctionnelle
Faire un jeu de questions/réponses. Il y aura plusieurs catégories de question (les Topics). Chaque question a entre 2 et 4 réponses possible.
Le joueur doit simplement sélectionner la réponse qu'il juge être la meilleure. Une fois que le joueur a répondu, les statistiques de la questions
s'affichent (statistiques = le pourcentage par réponse).

== Conception technique
=== Technologies
* Spring Boot 2
* PostgreSQL 10
* Docker

=== Objectifs
* Utiliser les différentes possibilités qu'offre Spring Boot pour les DAO (JpaRepository, @Query, ...)

=== Base de données
(réf.: `_src > main > sql > init > init-db.sql_`)

Les tables:

* topic
* question
* answer


=== Webservices
`_/best-choice_`::
* `/topic-list`
* `/question-list-by-notopic`
* `/answer-list-by-noquestion`

=== DAO
`QuestionDao`:: Exemple de DAO où les queries sont définies par le nom de la méthode
`AnswerDao`:: Exemple de DAO où les queries sont définies dans l'annotation @Query

=== Docker
Remarque: changer le host de la DB dans les properties du back: `jdbc:postgresql://localhost:5432/games_app` -> `jdbc:postgresql://best-choice-psql-db:5432/games_app`

Pour récupérer les images postgres et :

* `docker pull postgres`
* ``

Pour créer notre image docker pour notre base de données PostgreSQL:

* docker run -p 5432:5432 --name best-choice-psql-db -e POSTGRES_PASSWORD=postgres -d --volumes-from PostgresData postgres

Pour faire un premier build de notre application _**best-choice-backend**_:

* Pour créer la docker image (doit se faire à la racine du projet, car c'est là qu'il y a le Dockerfile): `docker build . -t best-choice-backend`
* Pour voir les docker images: `docker images`
* Pour démarrer l'image docker et la relier à l'image docker de postgres: `docker run -p 8080:8080 --name best-choice-backend --link best-choice-psql-db:postgres -d best-choice-backend`
* Pour voir les docker container: `docker container ls`
* Pour les logs d'un docker: `docker logs best-choice-psql-db` ou `docker logs best-choice-backend`

Pour rebuild notre application _**best-choice-backend**_:

* On stop: `docker stop best-choice-backend`
* On supprime le container: `docker container rm container_id` (pour récupérer l'id du container on fait un `docker ps`)
* On supprime l'image: `docker image rm best-choice-backend`
* On recrée l'image docker de notre application: `docker build . -t best-choice-backend`
* On recrée le container de l'app.: `docker run -p 8080:8080 --name best-choice-backend --link best-choice-psql-db:postgres -d best-choice-backend`
